modLoader="javafml"
loaderVersion="[27,)"
#issueTrackerURL="http://my.issue.tracker/"
#displayURL="http://example.com/"
logoFile="torcherino.png" #optional

[[mods]]
  modId="torcherino"
  version="${file.jarVersion}"
  displayName="Torcherino"
  updateJSONURL="https://raw.githubusercontent.com/NinjaPhenix/Torcherino/1.14.3-forge/update.json"
  description="Adds blocks which speed up tile entities."
  authors="NinjaPhenix1, sci4me, Moze_Intel"
  #credits="Thanks for this example mod goes to Java"
[[dependencies.torcherino]]
  modId="forge"
  mandatory=true
  versionRange="[27,)"
  ordering="NONE"
  side="BOTH"
[[dependencies.torcherino]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.14.3]"
  ordering="NONE"
  side="BOTH"