modLoader="javafml"
loaderVersion="[24,)"
#issueTrackerURL="http://my.issue.tracker/"
#displayURL="http://example.com/"
logoFile="torcherino.png" #optional

[[mods]]
  modId="torcherino"
  version="${file.jarVersion}"
  displayName="Torcherino"
  updateJSONURL="https://gist.githubusercontent.com/NinjaPhenix/2e4f1700a605b03922833dc57a6afac9/raw/5aeaab58221870943dc2c481438d4346106051d4/ForgeUpdate.json"
  description="Adds blocks which speed up tile entities."
  authors="NinjaPhenix1, sci4me, Moze_Intel"
  #credits="Thanks for this example mod goes to Java"
[[dependencies.torcherino]]
  modId="forge"
  mandatory=true
  versionRange="[24,)"
  ordering="NONE"
  side="BOTH"
[[dependencies.torcherino]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.13.2]"
  ordering="NONE"
  side="BOTH"