modLoader="javafml"
loaderVersion="[24,)"
#issueTrackerURL="http://my.issue.tracker/"
#displayURL="http://example.com/"
logoFile="torcherino.png" #optional

[[mods]]
  modId="torcherino"
  version="${file.jarVersion}"
  displayName="Torcherino"
  updateJSONURL="https://blanket.troi.webdock.io/forge-update.json"
  description="Adds blocks which speed up tile entities."
  authors="NinjaPhenix1, sci4me, Moze_Intel"
  #credits="Thanks for this example mod goes to Java"
[[dependencies.torcherino]]
  modId="forge"
  mandatory=true
  versionRange="[24,)"
  ordering="NONE"
  side="BOTH"
[[dependencies.torcherino]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.13.2]"
  ordering="NONE"
  side="BOTH"